.\"                             -*- Mode: Nroff -*- 
.\" Copyright (C) 2000 Manoj Srivastava <srivasta@debian.org>.
.\"
.\" Permission is granted to make and distribute verbatim copies of
.\" this manual provided the copyright notice and this permission notice
.\" are preserved on all copies.
.\" 
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the entire
.\" resulting derived work is distributed under the terms of a permission
.\" notice identical to this one.
.\" 
.\" Permission is granted to copy and distribute translations of this manual
.\" into another language, under the above conditions for modified versions,
.\" except that this permission notice may be stated in a translation approved
.\" by the Author.
.\"
.\" Author: Manoj Srivastava
.\"
.\" arch-tag: cfe27e82-b7a5-4171-bef6-f7bc28306374
.\"
.TH QP\-DECODE 1 "Sep 2 2000" "Debian" "Debian GNU/Linux manual"
.SH NAME 
qp\-decode \- Fast Quoted Printable decoder
.SH SYNOPSIS
.B qp\-decode 
< 
.I qp\-encoded data
> 
.I converted output
.SH DESCRIPTION
The
.B qp\-decode
utility takes Quoted Printable data on the standard input and converts
it to the  standard output. 
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.SH OPTIONS
.B qp\-encode
does not take any arguments or options.
.SH BUGS
None known.
.SH SEE ALSO
.I qp\-encode (1)
.SH AUTHORS
.B qp\-decode
was written by Kyle Jones. and placed by him into the public domain.
This manual page was written by Manoj Srivastava <srivasta@debian.org>,
for the Debian GNU/Linux system.

